spring:
  datasource:
    url: jdbc:mysql://localhost:3306/redisdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root           # 修改填写
    password: root         # 修改填写
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 5
    maxActive: 100
    initialSize: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    removeAbandoned: true
    filters: stat # ,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
    cachePrepStmts: true  # 开启二级缓存
mybatis:
  typeAliasesPackage: com.it.springboot.pojo      # 需要学员自己修改填写
  mapperLocations: classpath:/com/it/springboot/dao/*.xml
  mapperScanPackage: com.it.springboot.dao
  configLocation: classpath:/mybatis-config.xml